# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# name: .NET

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 8.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 设置.NET版本
    - name: Set up.NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    # 编译项目
    - name: Compile
      run: dotnet publish -c release 

    # 创建制品目录
    - name: Create artifact directory
      run: mkdir -p artifacts

    # 复制生成的dll文件到制品目录，假设生成的文件在bin目录下，根据实际情况调整
    - name: Copy dll file
      run: cp /home/runner/work/dotnetcore-docs-hello-world-donet/dotnetcore-docs-hello-world-donet/bin/release/net8.0/dotnetcoresample.dll artifacts/

    # 上传制品
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-project-artifacts
        path: artifacts
